services:
  db:
    image: mysql:latest
    container_name: studiozero-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: studiozero
      MYSQL_DATABASE: studiozero
    ports:
      - "3308:3306"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: studiozero-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
